import json
import os

CONTEXT_PROMPT="""
    Image artifacts refer to unintended, implausible, or visibly corrupted regions within images generated by diffusion models. These artifacts often break the natural semantics or visual coherence of an image, such as a person with extra fingers, a car with warped wheels, or missing parts of animals, and can significantly degrade image quality or realism. Artifacts are a critical concern in both model evaluation and training.

    There are three types of image artifacts: Addition, Removal, and Distortion.

    1. Addition: Involves duplicating an existing part of the image and placing it somewhere else, creating implausible duplication (e.g., extra thumb, leg, or ear). The added part is placed adjacent to the original, in one of four directions. 
        - Common on peripheral or terminal parts of objects/entities:
            - Human/Animal: fingers, hands, toes, ears, etc.
            - Vehicles: mirrors, wheels, wipers.

    2. Removal: A specific object or part is deleted, and the area is inpainted using background textures, resulting in missing limbs, features, or objects, sometimes with visible traces.
        - Common on terminal or protruding elements:
            - Human/Animal: fingers, toes, legs, ears, horns, etc.
            - Vehicles: antennas, side mirrors, etc.

    3. Distortion: The object or part remains in place but the structure is altered (e.g., twisted, warped, scrambled), making the object unrecognizable or visually broken, like a warped face or twisted wheel.
        - Can occur anywhere, especially in central or continuous regions:
            - Human/Animal: face, torso, entire leg, etc.
            - Vehicles: car doors, etc.
"""

def convert_to_sft_format(data_dir, output_json):
    dataset = []
    for root, dirs, files in os.walk(data_dir):
        # print(root, dirs, files)
        if "image" not in os.path.basename(root):
            continue  # Skip non-image folders

        metadata_path = os.path.join(root, "metadata.json")
        image_path = os.path.join(root, "artifact_image.png")

        # print(metadata_path, image_path)
        if not os.path.exists(metadata_path) or not os.path.exists(image_path):
            continue  # Skip incomplete entries

        with open(metadata_path, "r") as f:
            metadata = json.load(f)

        bbox = metadata["target_bbox"]
        artifact_type = metadata["artifact_type"]
        entity = metadata["entity"]
        sub_entity = metadata["part_entity"]
        # explanation = metadata["explanation"]
        output_dict = [{
            "bbox_2d": bbox,
            "artifact_type": artifact_type,
            "explanation": f'The image contains an artifact of type {artifact_type} on the {sub_entity} of the {entity}.'
        }]

        output_template_dict =[{
            "bbox_2d": "[x_min, y_min, x_max, y_max]",
            "artifact_type": "Addition | Removal | Distortion",
            "explanation": "The image contains an artifact of type ... on the ... of the ...."
        }]

        value = f"```json\n{json.dumps(output_dict, indent=4)}\n```"
        json_template = f"```json\n{json.dumps(output_template_dict, indent=4)}\n```"

        dataset.append({
            "images": [image_path],
            "conversations": [
                {
                    "from": "human",
                    "value": "<image>Analyze the image and describe any visual anomalies. Provide bounding boxes, and the type of artifact. Respond in the following structured format: " + json_template
                },
                {
                    "from": "gpt",
                    "value": value
                }
            ],
            "system": CONTEXT_PROMPT
        })

    with open(output_json, "w") as f:
        json.dump(dataset, f, indent=2)

convert_to_sft_format(
    "/home/jovyan/image-artifacts/src/train/LLaMA-Factory/data/artifacts", 
    "image_artifacts_zero_shot.json"
)